// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.mcel2.domain;

import com.mcel2.domain.Accesories;

privileged aspect Accesories_Roo_JavaBean {
    
    public String Accesories.getName() {
        return this.name;
    }
    
    public void Accesories.setName(String name) {
        this.name = name;
    }
    
}
