// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.mcel2.domain;

import com.mcel2.domain.Contract;

privileged aspect Contract_Roo_JavaBean {
    
    public String Contract.getSerialNumber() {
        return this.serialNumber;
    }
    
    public void Contract.setSerialNumber(String serialNumber) {
        this.serialNumber = serialNumber;
    }
    
}
