// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.mcel2.domain;

import com.mcel2.domain.DiagnosisItems;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect DiagnosisItems_Roo_Configurable {
    
    declare @type: DiagnosisItems: @Configurable;
    
}
