// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.mcel2.domain;

import com.mcel2.domain.PossibleFailures;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect PossibleFailures_Roo_Configurable {
    
    declare @type: PossibleFailures: @Configurable;
    
}
