// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.mcel2.domain;

import com.mcel2.domain.ProductFamily;

privileged aspect ProductFamily_Roo_JavaBean {
    
    public String ProductFamily.getName() {
        return this.name;
    }
    
    public void ProductFamily.setName(String name) {
        this.name = name;
    }
    
}
