// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.mcel2.domain;

import com.mcel2.domain.ProductBrand;

privileged aspect ProductBrand_Roo_JavaBean {
    
    public String ProductBrand.getName() {
        return this.name;
    }
    
    public void ProductBrand.setName(String name) {
        this.name = name;
    }
    
}
