// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.mcel2.domain;

import com.mcel2.domain.Contract;
import com.mcel2.domain.ContractDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect ContractDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ContractDataOnDemand: @Component;
    
    private Random ContractDataOnDemand.rnd = new SecureRandom();
    
    private List<Contract> ContractDataOnDemand.data;
    
    public Contract ContractDataOnDemand.getNewTransientContract(int index) {
        Contract obj = new Contract();
        setSerialNumber(obj, index);
        return obj;
    }
    
    public void ContractDataOnDemand.setSerialNumber(Contract obj, int index) {
        String serialNumber = "serialNumber_" + index;
        obj.setSerialNumber(serialNumber);
    }
    
    public Contract ContractDataOnDemand.getSpecificContract(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Contract obj = data.get(index);
        Long id = obj.getId();
        return Contract.findContract(id);
    }
    
    public Contract ContractDataOnDemand.getRandomContract() {
        init();
        Contract obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Contract.findContract(id);
    }
    
    public boolean ContractDataOnDemand.modifyContract(Contract obj) {
        return false;
    }
    
    public void ContractDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Contract.findContractEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Contract' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Contract>();
        for (int i = 0; i < 10; i++) {
            Contract obj = getNewTransientContract(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
