// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.mcel2.domain;

import com.mcel2.domain.CustomerAddress;
import com.mcel2.domain.CustomerAddressDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect CustomerAddressDataOnDemand_Roo_DataOnDemand {
    
    declare @type: CustomerAddressDataOnDemand: @Component;
    
    private Random CustomerAddressDataOnDemand.rnd = new SecureRandom();
    
    private List<CustomerAddress> CustomerAddressDataOnDemand.data;
    
    public CustomerAddress CustomerAddressDataOnDemand.getNewTransientCustomerAddress(int index) {
        CustomerAddress obj = new CustomerAddress();
        setAddressReferences(obj, index);
        setColony(obj, index);
        setCountryState(obj, index);
        setDelegacion(obj, index);
        setExtNumber(obj, index);
        setIntNumber(obj, index);
        setStreet(obj, index);
        setZipCode(obj, index);
        return obj;
    }
    
    public void CustomerAddressDataOnDemand.setAddressReferences(CustomerAddress obj, int index) {
        String addressReferences = "addressReferences_" + index;
        obj.setAddressReferences(addressReferences);
    }
    
    public void CustomerAddressDataOnDemand.setColony(CustomerAddress obj, int index) {
        String colony = "colony_" + index;
        obj.setColony(colony);
    }
    
    public void CustomerAddressDataOnDemand.setCountryState(CustomerAddress obj, int index) {
        String countryState = "countryState_" + index;
        obj.setCountryState(countryState);
    }
    
    public void CustomerAddressDataOnDemand.setDelegacion(CustomerAddress obj, int index) {
        String delegacion = "delegacion_" + index;
        obj.setDelegacion(delegacion);
    }
    
    public void CustomerAddressDataOnDemand.setExtNumber(CustomerAddress obj, int index) {
        String extNumber = "extNumber_" + index;
        obj.setExtNumber(extNumber);
    }
    
    public void CustomerAddressDataOnDemand.setIntNumber(CustomerAddress obj, int index) {
        String intNumber = "intNumber_" + index;
        obj.setIntNumber(intNumber);
    }
    
    public void CustomerAddressDataOnDemand.setStreet(CustomerAddress obj, int index) {
        String street = "street_" + index;
        obj.setStreet(street);
    }
    
    public void CustomerAddressDataOnDemand.setZipCode(CustomerAddress obj, int index) {
        String zipCode = "zipCode_" + index;
        obj.setZipCode(zipCode);
    }
    
    public CustomerAddress CustomerAddressDataOnDemand.getSpecificCustomerAddress(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        CustomerAddress obj = data.get(index);
        Long id = obj.getId();
        return CustomerAddress.findCustomerAddress(id);
    }
    
    public CustomerAddress CustomerAddressDataOnDemand.getRandomCustomerAddress() {
        init();
        CustomerAddress obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return CustomerAddress.findCustomerAddress(id);
    }
    
    public boolean CustomerAddressDataOnDemand.modifyCustomerAddress(CustomerAddress obj) {
        return false;
    }
    
    public void CustomerAddressDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = CustomerAddress.findCustomerAddressEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'CustomerAddress' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<CustomerAddress>();
        for (int i = 0; i < 10; i++) {
            CustomerAddress obj = getNewTransientCustomerAddress(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
