// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.mcel2.domain;

import com.mcel2.domain.DiagnosisType;
import com.mcel2.domain.DiagnosisTypeDataOnDemand;
import com.mcel2.domain.DiagnosisTypeIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect DiagnosisTypeIntegrationTest_Roo_IntegrationTest {
    
    declare @type: DiagnosisTypeIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: DiagnosisTypeIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: DiagnosisTypeIntegrationTest: @Transactional;
    
    @Autowired
    DiagnosisTypeDataOnDemand DiagnosisTypeIntegrationTest.dod;
    
    @Test
    public void DiagnosisTypeIntegrationTest.testCountDiagnosisTypes() {
        Assert.assertNotNull("Data on demand for 'DiagnosisType' failed to initialize correctly", dod.getRandomDiagnosisType());
        long count = DiagnosisType.countDiagnosisTypes();
        Assert.assertTrue("Counter for 'DiagnosisType' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void DiagnosisTypeIntegrationTest.testFindDiagnosisType() {
        DiagnosisType obj = dod.getRandomDiagnosisType();
        Assert.assertNotNull("Data on demand for 'DiagnosisType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'DiagnosisType' failed to provide an identifier", id);
        obj = DiagnosisType.findDiagnosisType(id);
        Assert.assertNotNull("Find method for 'DiagnosisType' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'DiagnosisType' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void DiagnosisTypeIntegrationTest.testFindAllDiagnosisTypes() {
        Assert.assertNotNull("Data on demand for 'DiagnosisType' failed to initialize correctly", dod.getRandomDiagnosisType());
        long count = DiagnosisType.countDiagnosisTypes();
        Assert.assertTrue("Too expensive to perform a find all test for 'DiagnosisType', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<DiagnosisType> result = DiagnosisType.findAllDiagnosisTypes();
        Assert.assertNotNull("Find all method for 'DiagnosisType' illegally returned null", result);
        Assert.assertTrue("Find all method for 'DiagnosisType' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void DiagnosisTypeIntegrationTest.testFindDiagnosisTypeEntries() {
        Assert.assertNotNull("Data on demand for 'DiagnosisType' failed to initialize correctly", dod.getRandomDiagnosisType());
        long count = DiagnosisType.countDiagnosisTypes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<DiagnosisType> result = DiagnosisType.findDiagnosisTypeEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'DiagnosisType' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'DiagnosisType' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void DiagnosisTypeIntegrationTest.testFlush() {
        DiagnosisType obj = dod.getRandomDiagnosisType();
        Assert.assertNotNull("Data on demand for 'DiagnosisType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'DiagnosisType' failed to provide an identifier", id);
        obj = DiagnosisType.findDiagnosisType(id);
        Assert.assertNotNull("Find method for 'DiagnosisType' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyDiagnosisType(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'DiagnosisType' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void DiagnosisTypeIntegrationTest.testMergeUpdate() {
        DiagnosisType obj = dod.getRandomDiagnosisType();
        Assert.assertNotNull("Data on demand for 'DiagnosisType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'DiagnosisType' failed to provide an identifier", id);
        obj = DiagnosisType.findDiagnosisType(id);
        boolean modified =  dod.modifyDiagnosisType(obj);
        Integer currentVersion = obj.getVersion();
        DiagnosisType merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'DiagnosisType' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void DiagnosisTypeIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'DiagnosisType' failed to initialize correctly", dod.getRandomDiagnosisType());
        DiagnosisType obj = dod.getNewTransientDiagnosisType(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'DiagnosisType' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'DiagnosisType' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'DiagnosisType' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void DiagnosisTypeIntegrationTest.testRemove() {
        DiagnosisType obj = dod.getRandomDiagnosisType();
        Assert.assertNotNull("Data on demand for 'DiagnosisType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'DiagnosisType' failed to provide an identifier", id);
        obj = DiagnosisType.findDiagnosisType(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'DiagnosisType' with identifier '" + id + "'", DiagnosisType.findDiagnosisType(id));
    }
    
}
