// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.mcel2.domain;

import com.mcel2.domain.DiagnosisItems;
import com.mcel2.domain.DiagnosisItemsDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect DiagnosisItemsDataOnDemand_Roo_DataOnDemand {
    
    declare @type: DiagnosisItemsDataOnDemand: @Component;
    
    private Random DiagnosisItemsDataOnDemand.rnd = new SecureRandom();
    
    private List<DiagnosisItems> DiagnosisItemsDataOnDemand.data;
    
    public DiagnosisItems DiagnosisItemsDataOnDemand.getNewTransientDiagnosisItems(int index) {
        DiagnosisItems obj = new DiagnosisItems();
        setDescription(obj, index);
        return obj;
    }
    
    public void DiagnosisItemsDataOnDemand.setDescription(DiagnosisItems obj, int index) {
        String description = "description_" + index;
        obj.setDescription(description);
    }
    
    public DiagnosisItems DiagnosisItemsDataOnDemand.getSpecificDiagnosisItems(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        DiagnosisItems obj = data.get(index);
        Long id = obj.getId();
        return DiagnosisItems.findDiagnosisItems(id);
    }
    
    public DiagnosisItems DiagnosisItemsDataOnDemand.getRandomDiagnosisItems() {
        init();
        DiagnosisItems obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return DiagnosisItems.findDiagnosisItems(id);
    }
    
    public boolean DiagnosisItemsDataOnDemand.modifyDiagnosisItems(DiagnosisItems obj) {
        return false;
    }
    
    public void DiagnosisItemsDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = DiagnosisItems.findDiagnosisItemsEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'DiagnosisItems' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<DiagnosisItems>();
        for (int i = 0; i < 10; i++) {
            DiagnosisItems obj = getNewTransientDiagnosisItems(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
