// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.mcel2.domain;

import com.mcel2.domain.DiagnosisType;
import com.mcel2.domain.DiagnosisTypeDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect DiagnosisTypeDataOnDemand_Roo_DataOnDemand {
    
    declare @type: DiagnosisTypeDataOnDemand: @Component;
    
    private Random DiagnosisTypeDataOnDemand.rnd = new SecureRandom();
    
    private List<DiagnosisType> DiagnosisTypeDataOnDemand.data;
    
    public DiagnosisType DiagnosisTypeDataOnDemand.getNewTransientDiagnosisType(int index) {
        DiagnosisType obj = new DiagnosisType();
        setDescription(obj, index);
        return obj;
    }
    
    public void DiagnosisTypeDataOnDemand.setDescription(DiagnosisType obj, int index) {
        String description = "description_" + index;
        obj.setDescription(description);
    }
    
    public DiagnosisType DiagnosisTypeDataOnDemand.getSpecificDiagnosisType(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        DiagnosisType obj = data.get(index);
        Long id = obj.getId();
        return DiagnosisType.findDiagnosisType(id);
    }
    
    public DiagnosisType DiagnosisTypeDataOnDemand.getRandomDiagnosisType() {
        init();
        DiagnosisType obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return DiagnosisType.findDiagnosisType(id);
    }
    
    public boolean DiagnosisTypeDataOnDemand.modifyDiagnosisType(DiagnosisType obj) {
        return false;
    }
    
    public void DiagnosisTypeDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = DiagnosisType.findDiagnosisTypeEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'DiagnosisType' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<DiagnosisType>();
        for (int i = 0; i < 10; i++) {
            DiagnosisType obj = getNewTransientDiagnosisType(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
