// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.mcel2.domain;

import com.mcel2.domain.DiagnosysServices;
import com.mcel2.domain.DiagnosysServicesDataOnDemand;
import com.mcel2.domain.DiagnosysServicesIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect DiagnosysServicesIntegrationTest_Roo_IntegrationTest {
    
    declare @type: DiagnosysServicesIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: DiagnosysServicesIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: DiagnosysServicesIntegrationTest: @Transactional;
    
    @Autowired
    DiagnosysServicesDataOnDemand DiagnosysServicesIntegrationTest.dod;
    
    @Test
    public void DiagnosysServicesIntegrationTest.testCountDiagnosysServiceses() {
        Assert.assertNotNull("Data on demand for 'DiagnosysServices' failed to initialize correctly", dod.getRandomDiagnosysServices());
        long count = DiagnosysServices.countDiagnosysServiceses();
        Assert.assertTrue("Counter for 'DiagnosysServices' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void DiagnosysServicesIntegrationTest.testFindDiagnosysServices() {
        DiagnosysServices obj = dod.getRandomDiagnosysServices();
        Assert.assertNotNull("Data on demand for 'DiagnosysServices' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'DiagnosysServices' failed to provide an identifier", id);
        obj = DiagnosysServices.findDiagnosysServices(id);
        Assert.assertNotNull("Find method for 'DiagnosysServices' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'DiagnosysServices' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void DiagnosysServicesIntegrationTest.testFindAllDiagnosysServiceses() {
        Assert.assertNotNull("Data on demand for 'DiagnosysServices' failed to initialize correctly", dod.getRandomDiagnosysServices());
        long count = DiagnosysServices.countDiagnosysServiceses();
        Assert.assertTrue("Too expensive to perform a find all test for 'DiagnosysServices', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<DiagnosysServices> result = DiagnosysServices.findAllDiagnosysServiceses();
        Assert.assertNotNull("Find all method for 'DiagnosysServices' illegally returned null", result);
        Assert.assertTrue("Find all method for 'DiagnosysServices' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void DiagnosysServicesIntegrationTest.testFindDiagnosysServicesEntries() {
        Assert.assertNotNull("Data on demand for 'DiagnosysServices' failed to initialize correctly", dod.getRandomDiagnosysServices());
        long count = DiagnosysServices.countDiagnosysServiceses();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<DiagnosysServices> result = DiagnosysServices.findDiagnosysServicesEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'DiagnosysServices' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'DiagnosysServices' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void DiagnosysServicesIntegrationTest.testFlush() {
        DiagnosysServices obj = dod.getRandomDiagnosysServices();
        Assert.assertNotNull("Data on demand for 'DiagnosysServices' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'DiagnosysServices' failed to provide an identifier", id);
        obj = DiagnosysServices.findDiagnosysServices(id);
        Assert.assertNotNull("Find method for 'DiagnosysServices' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyDiagnosysServices(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'DiagnosysServices' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void DiagnosysServicesIntegrationTest.testMergeUpdate() {
        DiagnosysServices obj = dod.getRandomDiagnosysServices();
        Assert.assertNotNull("Data on demand for 'DiagnosysServices' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'DiagnosysServices' failed to provide an identifier", id);
        obj = DiagnosysServices.findDiagnosysServices(id);
        boolean modified =  dod.modifyDiagnosysServices(obj);
        Integer currentVersion = obj.getVersion();
        DiagnosysServices merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'DiagnosysServices' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void DiagnosysServicesIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'DiagnosysServices' failed to initialize correctly", dod.getRandomDiagnosysServices());
        DiagnosysServices obj = dod.getNewTransientDiagnosysServices(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'DiagnosysServices' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'DiagnosysServices' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'DiagnosysServices' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void DiagnosysServicesIntegrationTest.testRemove() {
        DiagnosysServices obj = dod.getRandomDiagnosysServices();
        Assert.assertNotNull("Data on demand for 'DiagnosysServices' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'DiagnosysServices' failed to provide an identifier", id);
        obj = DiagnosysServices.findDiagnosysServices(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'DiagnosysServices' with identifier '" + id + "'", DiagnosysServices.findDiagnosysServices(id));
    }
    
}
