// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.mcel2.domain;

import com.mcel2.domain.PossibleFailuresType;
import com.mcel2.domain.PossibleFailuresTypeDataOnDemand;
import com.mcel2.domain.PossibleFailuresTypeIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect PossibleFailuresTypeIntegrationTest_Roo_IntegrationTest {
    
    declare @type: PossibleFailuresTypeIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: PossibleFailuresTypeIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: PossibleFailuresTypeIntegrationTest: @Transactional;
    
    @Autowired
    PossibleFailuresTypeDataOnDemand PossibleFailuresTypeIntegrationTest.dod;
    
    @Test
    public void PossibleFailuresTypeIntegrationTest.testCountPossibleFailuresTypes() {
        Assert.assertNotNull("Data on demand for 'PossibleFailuresType' failed to initialize correctly", dod.getRandomPossibleFailuresType());
        long count = PossibleFailuresType.countPossibleFailuresTypes();
        Assert.assertTrue("Counter for 'PossibleFailuresType' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void PossibleFailuresTypeIntegrationTest.testFindPossibleFailuresType() {
        PossibleFailuresType obj = dod.getRandomPossibleFailuresType();
        Assert.assertNotNull("Data on demand for 'PossibleFailuresType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'PossibleFailuresType' failed to provide an identifier", id);
        obj = PossibleFailuresType.findPossibleFailuresType(id);
        Assert.assertNotNull("Find method for 'PossibleFailuresType' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'PossibleFailuresType' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void PossibleFailuresTypeIntegrationTest.testFindAllPossibleFailuresTypes() {
        Assert.assertNotNull("Data on demand for 'PossibleFailuresType' failed to initialize correctly", dod.getRandomPossibleFailuresType());
        long count = PossibleFailuresType.countPossibleFailuresTypes();
        Assert.assertTrue("Too expensive to perform a find all test for 'PossibleFailuresType', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<PossibleFailuresType> result = PossibleFailuresType.findAllPossibleFailuresTypes();
        Assert.assertNotNull("Find all method for 'PossibleFailuresType' illegally returned null", result);
        Assert.assertTrue("Find all method for 'PossibleFailuresType' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void PossibleFailuresTypeIntegrationTest.testFindPossibleFailuresTypeEntries() {
        Assert.assertNotNull("Data on demand for 'PossibleFailuresType' failed to initialize correctly", dod.getRandomPossibleFailuresType());
        long count = PossibleFailuresType.countPossibleFailuresTypes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<PossibleFailuresType> result = PossibleFailuresType.findPossibleFailuresTypeEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'PossibleFailuresType' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'PossibleFailuresType' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void PossibleFailuresTypeIntegrationTest.testFlush() {
        PossibleFailuresType obj = dod.getRandomPossibleFailuresType();
        Assert.assertNotNull("Data on demand for 'PossibleFailuresType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'PossibleFailuresType' failed to provide an identifier", id);
        obj = PossibleFailuresType.findPossibleFailuresType(id);
        Assert.assertNotNull("Find method for 'PossibleFailuresType' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyPossibleFailuresType(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'PossibleFailuresType' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PossibleFailuresTypeIntegrationTest.testMergeUpdate() {
        PossibleFailuresType obj = dod.getRandomPossibleFailuresType();
        Assert.assertNotNull("Data on demand for 'PossibleFailuresType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'PossibleFailuresType' failed to provide an identifier", id);
        obj = PossibleFailuresType.findPossibleFailuresType(id);
        boolean modified =  dod.modifyPossibleFailuresType(obj);
        Integer currentVersion = obj.getVersion();
        PossibleFailuresType merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'PossibleFailuresType' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PossibleFailuresTypeIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'PossibleFailuresType' failed to initialize correctly", dod.getRandomPossibleFailuresType());
        PossibleFailuresType obj = dod.getNewTransientPossibleFailuresType(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'PossibleFailuresType' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'PossibleFailuresType' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'PossibleFailuresType' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void PossibleFailuresTypeIntegrationTest.testRemove() {
        PossibleFailuresType obj = dod.getRandomPossibleFailuresType();
        Assert.assertNotNull("Data on demand for 'PossibleFailuresType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'PossibleFailuresType' failed to provide an identifier", id);
        obj = PossibleFailuresType.findPossibleFailuresType(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'PossibleFailuresType' with identifier '" + id + "'", PossibleFailuresType.findPossibleFailuresType(id));
    }
    
}
