// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.mcel2.domain;

import com.mcel2.domain.ProductCosmeticState;
import com.mcel2.domain.ProductCosmeticStateDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect ProductCosmeticStateDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ProductCosmeticStateDataOnDemand: @Component;
    
    private Random ProductCosmeticStateDataOnDemand.rnd = new SecureRandom();
    
    private List<ProductCosmeticState> ProductCosmeticStateDataOnDemand.data;
    
    public ProductCosmeticState ProductCosmeticStateDataOnDemand.getNewTransientProductCosmeticState(int index) {
        ProductCosmeticState obj = new ProductCosmeticState();
        setDescription(obj, index);
        return obj;
    }
    
    public void ProductCosmeticStateDataOnDemand.setDescription(ProductCosmeticState obj, int index) {
        String description = "description_" + index;
        obj.setDescription(description);
    }
    
    public ProductCosmeticState ProductCosmeticStateDataOnDemand.getSpecificProductCosmeticState(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        ProductCosmeticState obj = data.get(index);
        Long id = obj.getId();
        return ProductCosmeticState.findProductCosmeticState(id);
    }
    
    public ProductCosmeticState ProductCosmeticStateDataOnDemand.getRandomProductCosmeticState() {
        init();
        ProductCosmeticState obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return ProductCosmeticState.findProductCosmeticState(id);
    }
    
    public boolean ProductCosmeticStateDataOnDemand.modifyProductCosmeticState(ProductCosmeticState obj) {
        return false;
    }
    
    public void ProductCosmeticStateDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = ProductCosmeticState.findProductCosmeticStateEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'ProductCosmeticState' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<ProductCosmeticState>();
        for (int i = 0; i < 10; i++) {
            ProductCosmeticState obj = getNewTransientProductCosmeticState(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
