// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.mcel2.domain;

import com.mcel2.domain.ProductColor;
import com.mcel2.domain.ProductColorDataOnDemand;
import com.mcel2.domain.ProductColorIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ProductColorIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ProductColorIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ProductColorIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ProductColorIntegrationTest: @Transactional;
    
    @Autowired
    ProductColorDataOnDemand ProductColorIntegrationTest.dod;
    
    @Test
    public void ProductColorIntegrationTest.testCountProductColors() {
        Assert.assertNotNull("Data on demand for 'ProductColor' failed to initialize correctly", dod.getRandomProductColor());
        long count = ProductColor.countProductColors();
        Assert.assertTrue("Counter for 'ProductColor' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ProductColorIntegrationTest.testFindProductColor() {
        ProductColor obj = dod.getRandomProductColor();
        Assert.assertNotNull("Data on demand for 'ProductColor' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ProductColor' failed to provide an identifier", id);
        obj = ProductColor.findProductColor(id);
        Assert.assertNotNull("Find method for 'ProductColor' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'ProductColor' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ProductColorIntegrationTest.testFindAllProductColors() {
        Assert.assertNotNull("Data on demand for 'ProductColor' failed to initialize correctly", dod.getRandomProductColor());
        long count = ProductColor.countProductColors();
        Assert.assertTrue("Too expensive to perform a find all test for 'ProductColor', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<ProductColor> result = ProductColor.findAllProductColors();
        Assert.assertNotNull("Find all method for 'ProductColor' illegally returned null", result);
        Assert.assertTrue("Find all method for 'ProductColor' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ProductColorIntegrationTest.testFindProductColorEntries() {
        Assert.assertNotNull("Data on demand for 'ProductColor' failed to initialize correctly", dod.getRandomProductColor());
        long count = ProductColor.countProductColors();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<ProductColor> result = ProductColor.findProductColorEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'ProductColor' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'ProductColor' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ProductColorIntegrationTest.testFlush() {
        ProductColor obj = dod.getRandomProductColor();
        Assert.assertNotNull("Data on demand for 'ProductColor' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ProductColor' failed to provide an identifier", id);
        obj = ProductColor.findProductColor(id);
        Assert.assertNotNull("Find method for 'ProductColor' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyProductColor(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'ProductColor' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ProductColorIntegrationTest.testMergeUpdate() {
        ProductColor obj = dod.getRandomProductColor();
        Assert.assertNotNull("Data on demand for 'ProductColor' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ProductColor' failed to provide an identifier", id);
        obj = ProductColor.findProductColor(id);
        boolean modified =  dod.modifyProductColor(obj);
        Integer currentVersion = obj.getVersion();
        ProductColor merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'ProductColor' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ProductColorIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'ProductColor' failed to initialize correctly", dod.getRandomProductColor());
        ProductColor obj = dod.getNewTransientProductColor(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'ProductColor' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'ProductColor' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'ProductColor' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ProductColorIntegrationTest.testRemove() {
        ProductColor obj = dod.getRandomProductColor();
        Assert.assertNotNull("Data on demand for 'ProductColor' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ProductColor' failed to provide an identifier", id);
        obj = ProductColor.findProductColor(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'ProductColor' with identifier '" + id + "'", ProductColor.findProductColor(id));
    }
    
}
