// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.mcel2.domain;

import com.mcel2.domain.ProductFamilyDataOnDemand;
import com.mcel2.domain.ProductSubFamily;
import com.mcel2.domain.ProductSubFamilyDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect ProductSubFamilyDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ProductSubFamilyDataOnDemand: @Component;
    
    private Random ProductSubFamilyDataOnDemand.rnd = new SecureRandom();
    
    private List<ProductSubFamily> ProductSubFamilyDataOnDemand.data;
    
    @Autowired
    ProductFamilyDataOnDemand ProductSubFamilyDataOnDemand.productFamilyDataOnDemand;
    
    public ProductSubFamily ProductSubFamilyDataOnDemand.getNewTransientProductSubFamily(int index) {
        ProductSubFamily obj = new ProductSubFamily();
        setName(obj, index);
        return obj;
    }
    
    public void ProductSubFamilyDataOnDemand.setName(ProductSubFamily obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public ProductSubFamily ProductSubFamilyDataOnDemand.getSpecificProductSubFamily(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        ProductSubFamily obj = data.get(index);
        Long id = obj.getId();
        return ProductSubFamily.findProductSubFamily(id);
    }
    
    public ProductSubFamily ProductSubFamilyDataOnDemand.getRandomProductSubFamily() {
        init();
        ProductSubFamily obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return ProductSubFamily.findProductSubFamily(id);
    }
    
    public boolean ProductSubFamilyDataOnDemand.modifyProductSubFamily(ProductSubFamily obj) {
        return false;
    }
    
    public void ProductSubFamilyDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = ProductSubFamily.findProductSubFamilyEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'ProductSubFamily' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<ProductSubFamily>();
        for (int i = 0; i < 10; i++) {
            ProductSubFamily obj = getNewTransientProductSubFamily(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
