// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.mcel2.domain;

import com.mcel2.domain.ProductSubFamily;
import com.mcel2.domain.ProductSubFamilyDataOnDemand;
import com.mcel2.domain.ProductSubFamilyIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ProductSubFamilyIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ProductSubFamilyIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ProductSubFamilyIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ProductSubFamilyIntegrationTest: @Transactional;
    
    @Autowired
    ProductSubFamilyDataOnDemand ProductSubFamilyIntegrationTest.dod;
    
    @Test
    public void ProductSubFamilyIntegrationTest.testCountProductSubFamilys() {
        Assert.assertNotNull("Data on demand for 'ProductSubFamily' failed to initialize correctly", dod.getRandomProductSubFamily());
        long count = ProductSubFamily.countProductSubFamilys();
        Assert.assertTrue("Counter for 'ProductSubFamily' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ProductSubFamilyIntegrationTest.testFindProductSubFamily() {
        ProductSubFamily obj = dod.getRandomProductSubFamily();
        Assert.assertNotNull("Data on demand for 'ProductSubFamily' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ProductSubFamily' failed to provide an identifier", id);
        obj = ProductSubFamily.findProductSubFamily(id);
        Assert.assertNotNull("Find method for 'ProductSubFamily' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'ProductSubFamily' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ProductSubFamilyIntegrationTest.testFindAllProductSubFamilys() {
        Assert.assertNotNull("Data on demand for 'ProductSubFamily' failed to initialize correctly", dod.getRandomProductSubFamily());
        long count = ProductSubFamily.countProductSubFamilys();
        Assert.assertTrue("Too expensive to perform a find all test for 'ProductSubFamily', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<ProductSubFamily> result = ProductSubFamily.findAllProductSubFamilys();
        Assert.assertNotNull("Find all method for 'ProductSubFamily' illegally returned null", result);
        Assert.assertTrue("Find all method for 'ProductSubFamily' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ProductSubFamilyIntegrationTest.testFindProductSubFamilyEntries() {
        Assert.assertNotNull("Data on demand for 'ProductSubFamily' failed to initialize correctly", dod.getRandomProductSubFamily());
        long count = ProductSubFamily.countProductSubFamilys();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<ProductSubFamily> result = ProductSubFamily.findProductSubFamilyEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'ProductSubFamily' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'ProductSubFamily' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ProductSubFamilyIntegrationTest.testFlush() {
        ProductSubFamily obj = dod.getRandomProductSubFamily();
        Assert.assertNotNull("Data on demand for 'ProductSubFamily' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ProductSubFamily' failed to provide an identifier", id);
        obj = ProductSubFamily.findProductSubFamily(id);
        Assert.assertNotNull("Find method for 'ProductSubFamily' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyProductSubFamily(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'ProductSubFamily' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ProductSubFamilyIntegrationTest.testMergeUpdate() {
        ProductSubFamily obj = dod.getRandomProductSubFamily();
        Assert.assertNotNull("Data on demand for 'ProductSubFamily' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ProductSubFamily' failed to provide an identifier", id);
        obj = ProductSubFamily.findProductSubFamily(id);
        boolean modified =  dod.modifyProductSubFamily(obj);
        Integer currentVersion = obj.getVersion();
        ProductSubFamily merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'ProductSubFamily' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ProductSubFamilyIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'ProductSubFamily' failed to initialize correctly", dod.getRandomProductSubFamily());
        ProductSubFamily obj = dod.getNewTransientProductSubFamily(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'ProductSubFamily' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'ProductSubFamily' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'ProductSubFamily' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ProductSubFamilyIntegrationTest.testRemove() {
        ProductSubFamily obj = dod.getRandomProductSubFamily();
        Assert.assertNotNull("Data on demand for 'ProductSubFamily' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ProductSubFamily' failed to provide an identifier", id);
        obj = ProductSubFamily.findProductSubFamily(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'ProductSubFamily' with identifier '" + id + "'", ProductSubFamily.findProductSubFamily(id));
    }
    
}
