// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.mcel2.domain;

import com.mcel2.domain.ProductColor;
import com.mcel2.domain.ProductColorDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect ProductColorDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ProductColorDataOnDemand: @Component;
    
    private Random ProductColorDataOnDemand.rnd = new SecureRandom();
    
    private List<ProductColor> ProductColorDataOnDemand.data;
    
    public ProductColor ProductColorDataOnDemand.getNewTransientProductColor(int index) {
        ProductColor obj = new ProductColor();
        setColor(obj, index);
        return obj;
    }
    
    public void ProductColorDataOnDemand.setColor(ProductColor obj, int index) {
        String color = "color_" + index;
        obj.setColor(color);
    }
    
    public ProductColor ProductColorDataOnDemand.getSpecificProductColor(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        ProductColor obj = data.get(index);
        Long id = obj.getId();
        return ProductColor.findProductColor(id);
    }
    
    public ProductColor ProductColorDataOnDemand.getRandomProductColor() {
        init();
        ProductColor obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return ProductColor.findProductColor(id);
    }
    
    public boolean ProductColorDataOnDemand.modifyProductColor(ProductColor obj) {
        return false;
    }
    
    public void ProductColorDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = ProductColor.findProductColorEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'ProductColor' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<ProductColor>();
        for (int i = 0; i < 10; i++) {
            ProductColor obj = getNewTransientProductColor(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
