// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.mcel2.domain;

import com.mcel2.domain.ProductBrand;
import com.mcel2.domain.ProductBrandDataOnDemand;
import com.mcel2.domain.ProductBrandIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ProductBrandIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ProductBrandIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ProductBrandIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ProductBrandIntegrationTest: @Transactional;
    
    @Autowired
    ProductBrandDataOnDemand ProductBrandIntegrationTest.dod;
    
    @Test
    public void ProductBrandIntegrationTest.testCountProductBrands() {
        Assert.assertNotNull("Data on demand for 'ProductBrand' failed to initialize correctly", dod.getRandomProductBrand());
        long count = ProductBrand.countProductBrands();
        Assert.assertTrue("Counter for 'ProductBrand' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ProductBrandIntegrationTest.testFindProductBrand() {
        ProductBrand obj = dod.getRandomProductBrand();
        Assert.assertNotNull("Data on demand for 'ProductBrand' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ProductBrand' failed to provide an identifier", id);
        obj = ProductBrand.findProductBrand(id);
        Assert.assertNotNull("Find method for 'ProductBrand' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'ProductBrand' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ProductBrandIntegrationTest.testFindAllProductBrands() {
        Assert.assertNotNull("Data on demand for 'ProductBrand' failed to initialize correctly", dod.getRandomProductBrand());
        long count = ProductBrand.countProductBrands();
        Assert.assertTrue("Too expensive to perform a find all test for 'ProductBrand', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<ProductBrand> result = ProductBrand.findAllProductBrands();
        Assert.assertNotNull("Find all method for 'ProductBrand' illegally returned null", result);
        Assert.assertTrue("Find all method for 'ProductBrand' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ProductBrandIntegrationTest.testFindProductBrandEntries() {
        Assert.assertNotNull("Data on demand for 'ProductBrand' failed to initialize correctly", dod.getRandomProductBrand());
        long count = ProductBrand.countProductBrands();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<ProductBrand> result = ProductBrand.findProductBrandEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'ProductBrand' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'ProductBrand' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ProductBrandIntegrationTest.testFlush() {
        ProductBrand obj = dod.getRandomProductBrand();
        Assert.assertNotNull("Data on demand for 'ProductBrand' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ProductBrand' failed to provide an identifier", id);
        obj = ProductBrand.findProductBrand(id);
        Assert.assertNotNull("Find method for 'ProductBrand' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyProductBrand(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'ProductBrand' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ProductBrandIntegrationTest.testMergeUpdate() {
        ProductBrand obj = dod.getRandomProductBrand();
        Assert.assertNotNull("Data on demand for 'ProductBrand' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ProductBrand' failed to provide an identifier", id);
        obj = ProductBrand.findProductBrand(id);
        boolean modified =  dod.modifyProductBrand(obj);
        Integer currentVersion = obj.getVersion();
        ProductBrand merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'ProductBrand' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ProductBrandIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'ProductBrand' failed to initialize correctly", dod.getRandomProductBrand());
        ProductBrand obj = dod.getNewTransientProductBrand(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'ProductBrand' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'ProductBrand' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'ProductBrand' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ProductBrandIntegrationTest.testRemove() {
        ProductBrand obj = dod.getRandomProductBrand();
        Assert.assertNotNull("Data on demand for 'ProductBrand' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ProductBrand' failed to provide an identifier", id);
        obj = ProductBrand.findProductBrand(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'ProductBrand' with identifier '" + id + "'", ProductBrand.findProductBrand(id));
    }
    
}
