// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.mcel2.domain;

import com.mcel2.domain.ProductBrand;
import com.mcel2.domain.ProductBrandDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect ProductBrandDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ProductBrandDataOnDemand: @Component;
    
    private Random ProductBrandDataOnDemand.rnd = new SecureRandom();
    
    private List<ProductBrand> ProductBrandDataOnDemand.data;
    
    public ProductBrand ProductBrandDataOnDemand.getNewTransientProductBrand(int index) {
        ProductBrand obj = new ProductBrand();
        setName(obj, index);
        return obj;
    }
    
    public void ProductBrandDataOnDemand.setName(ProductBrand obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public ProductBrand ProductBrandDataOnDemand.getSpecificProductBrand(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        ProductBrand obj = data.get(index);
        Long id = obj.getId();
        return ProductBrand.findProductBrand(id);
    }
    
    public ProductBrand ProductBrandDataOnDemand.getRandomProductBrand() {
        init();
        ProductBrand obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return ProductBrand.findProductBrand(id);
    }
    
    public boolean ProductBrandDataOnDemand.modifyProductBrand(ProductBrand obj) {
        return false;
    }
    
    public void ProductBrandDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = ProductBrand.findProductBrandEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'ProductBrand' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<ProductBrand>();
        for (int i = 0; i < 10; i++) {
            ProductBrand obj = getNewTransientProductBrand(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
