// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.mcel2.domain;

import com.mcel2.domain.ServiceDiagnosys;
import com.mcel2.domain.ServiceDiagnosysDataOnDemand;
import com.mcel2.domain.ServiceOrderDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect ServiceDiagnosysDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ServiceDiagnosysDataOnDemand: @Component;
    
    private Random ServiceDiagnosysDataOnDemand.rnd = new SecureRandom();
    
    private List<ServiceDiagnosys> ServiceDiagnosysDataOnDemand.data;
    
    @Autowired
    ServiceOrderDataOnDemand ServiceDiagnosysDataOnDemand.serviceOrderDataOnDemand;
    
    public ServiceDiagnosys ServiceDiagnosysDataOnDemand.getNewTransientServiceDiagnosys(int index) {
        ServiceDiagnosys obj = new ServiceDiagnosys();
        setIrreparablePdf(obj, index);
        setPhotos(obj, index);
        return obj;
    }
    
    public void ServiceDiagnosysDataOnDemand.setIrreparablePdf(ServiceDiagnosys obj, int index) {
        byte[] irreparablePdf = String.valueOf(index).getBytes();
        obj.setIrreparablePdf(irreparablePdf);
    }
    
    public void ServiceDiagnosysDataOnDemand.setPhotos(ServiceDiagnosys obj, int index) {
        byte[] photos = String.valueOf(index).getBytes();
        obj.setPhotos(photos);
    }
    
    public ServiceDiagnosys ServiceDiagnosysDataOnDemand.getSpecificServiceDiagnosys(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        ServiceDiagnosys obj = data.get(index);
        Long id = obj.getId();
        return ServiceDiagnosys.findServiceDiagnosys(id);
    }
    
    public ServiceDiagnosys ServiceDiagnosysDataOnDemand.getRandomServiceDiagnosys() {
        init();
        ServiceDiagnosys obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return ServiceDiagnosys.findServiceDiagnosys(id);
    }
    
    public boolean ServiceDiagnosysDataOnDemand.modifyServiceDiagnosys(ServiceDiagnosys obj) {
        return false;
    }
    
    public void ServiceDiagnosysDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = ServiceDiagnosys.findServiceDiagnosysEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'ServiceDiagnosys' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<ServiceDiagnosys>();
        for (int i = 0; i < 10; i++) {
            ServiceDiagnosys obj = getNewTransientServiceDiagnosys(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
