// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.mcel2.domain;

import com.mcel2.domain.CustomerAddressDataOnDemand;
import com.mcel2.domain.CustomerDataOnDemand;
import com.mcel2.domain.ProductBrandDataOnDemand;
import com.mcel2.domain.ProductColorDataOnDemand;
import com.mcel2.domain.ProductFamilyDataOnDemand;
import com.mcel2.domain.ProductSubFamilyDataOnDemand;
import com.mcel2.domain.ServiceOrder;
import com.mcel2.domain.ServiceOrderDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect ServiceOrderDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ServiceOrderDataOnDemand: @Component;
    
    private Random ServiceOrderDataOnDemand.rnd = new SecureRandom();
    
    private List<ServiceOrder> ServiceOrderDataOnDemand.data;
    
    @Autowired
    CustomerAddressDataOnDemand ServiceOrderDataOnDemand.customerAddressDataOnDemand;
    
    @Autowired
    ProductBrandDataOnDemand ServiceOrderDataOnDemand.productBrandDataOnDemand;
    
    @Autowired
    ProductColorDataOnDemand ServiceOrderDataOnDemand.productColorDataOnDemand;
    
    @Autowired
    CustomerDataOnDemand ServiceOrderDataOnDemand.customerDataOnDemand;
    
    @Autowired
    ProductFamilyDataOnDemand ServiceOrderDataOnDemand.productFamilyDataOnDemand;
    
    @Autowired
    ProductSubFamilyDataOnDemand ServiceOrderDataOnDemand.productSubFamilyDataOnDemand;
    
    public ServiceOrder ServiceOrderDataOnDemand.getNewTransientServiceOrder(int index) {
        ServiceOrder obj = new ServiceOrder();
        setFrontDeskTicket(obj, index);
        setHomeOrInStoreDelivery(obj, index);
        setObservations(obj, index);
        setSerialNumber(obj, index);
        return obj;
    }
    
    public void ServiceOrderDataOnDemand.setFrontDeskTicket(ServiceOrder obj, int index) {
        String frontDeskTicket = "frontDeskTicket_" + index;
        obj.setFrontDeskTicket(frontDeskTicket);
    }
    
    public void ServiceOrderDataOnDemand.setHomeOrInStoreDelivery(ServiceOrder obj, int index) {
        Boolean homeOrInStoreDelivery = Boolean.TRUE;
        obj.setHomeOrInStoreDelivery(homeOrInStoreDelivery);
    }
    
    public void ServiceOrderDataOnDemand.setObservations(ServiceOrder obj, int index) {
        String observations = "observations_" + index;
        obj.setObservations(observations);
    }
    
    public void ServiceOrderDataOnDemand.setSerialNumber(ServiceOrder obj, int index) {
        String serialNumber = "serialNumber_" + index;
        obj.setSerialNumber(serialNumber);
    }
    
    public ServiceOrder ServiceOrderDataOnDemand.getSpecificServiceOrder(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        ServiceOrder obj = data.get(index);
        Long id = obj.getId();
        return ServiceOrder.findServiceOrder(id);
    }
    
    public ServiceOrder ServiceOrderDataOnDemand.getRandomServiceOrder() {
        init();
        ServiceOrder obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return ServiceOrder.findServiceOrder(id);
    }
    
    public boolean ServiceOrderDataOnDemand.modifyServiceOrder(ServiceOrder obj) {
        return false;
    }
    
    public void ServiceOrderDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = ServiceOrder.findServiceOrderEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'ServiceOrder' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<ServiceOrder>();
        for (int i = 0; i < 10; i++) {
            ServiceOrder obj = getNewTransientServiceOrder(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
