// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.mcel2.domain;

import com.mcel2.domain.ServiceOrder;
import com.mcel2.domain.ServiceOrderDataOnDemand;
import com.mcel2.domain.ServiceOrderIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ServiceOrderIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ServiceOrderIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ServiceOrderIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ServiceOrderIntegrationTest: @Transactional;
    
    @Autowired
    ServiceOrderDataOnDemand ServiceOrderIntegrationTest.dod;
    
    @Test
    public void ServiceOrderIntegrationTest.testCountServiceOrders() {
        Assert.assertNotNull("Data on demand for 'ServiceOrder' failed to initialize correctly", dod.getRandomServiceOrder());
        long count = ServiceOrder.countServiceOrders();
        Assert.assertTrue("Counter for 'ServiceOrder' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ServiceOrderIntegrationTest.testFindServiceOrder() {
        ServiceOrder obj = dod.getRandomServiceOrder();
        Assert.assertNotNull("Data on demand for 'ServiceOrder' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ServiceOrder' failed to provide an identifier", id);
        obj = ServiceOrder.findServiceOrder(id);
        Assert.assertNotNull("Find method for 'ServiceOrder' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'ServiceOrder' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ServiceOrderIntegrationTest.testFindAllServiceOrders() {
        Assert.assertNotNull("Data on demand for 'ServiceOrder' failed to initialize correctly", dod.getRandomServiceOrder());
        long count = ServiceOrder.countServiceOrders();
        Assert.assertTrue("Too expensive to perform a find all test for 'ServiceOrder', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<ServiceOrder> result = ServiceOrder.findAllServiceOrders();
        Assert.assertNotNull("Find all method for 'ServiceOrder' illegally returned null", result);
        Assert.assertTrue("Find all method for 'ServiceOrder' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ServiceOrderIntegrationTest.testFindServiceOrderEntries() {
        Assert.assertNotNull("Data on demand for 'ServiceOrder' failed to initialize correctly", dod.getRandomServiceOrder());
        long count = ServiceOrder.countServiceOrders();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<ServiceOrder> result = ServiceOrder.findServiceOrderEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'ServiceOrder' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'ServiceOrder' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ServiceOrderIntegrationTest.testFlush() {
        ServiceOrder obj = dod.getRandomServiceOrder();
        Assert.assertNotNull("Data on demand for 'ServiceOrder' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ServiceOrder' failed to provide an identifier", id);
        obj = ServiceOrder.findServiceOrder(id);
        Assert.assertNotNull("Find method for 'ServiceOrder' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyServiceOrder(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'ServiceOrder' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ServiceOrderIntegrationTest.testMergeUpdate() {
        ServiceOrder obj = dod.getRandomServiceOrder();
        Assert.assertNotNull("Data on demand for 'ServiceOrder' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ServiceOrder' failed to provide an identifier", id);
        obj = ServiceOrder.findServiceOrder(id);
        boolean modified =  dod.modifyServiceOrder(obj);
        Integer currentVersion = obj.getVersion();
        ServiceOrder merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'ServiceOrder' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ServiceOrderIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'ServiceOrder' failed to initialize correctly", dod.getRandomServiceOrder());
        ServiceOrder obj = dod.getNewTransientServiceOrder(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'ServiceOrder' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'ServiceOrder' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'ServiceOrder' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ServiceOrderIntegrationTest.testRemove() {
        ServiceOrder obj = dod.getRandomServiceOrder();
        Assert.assertNotNull("Data on demand for 'ServiceOrder' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ServiceOrder' failed to provide an identifier", id);
        obj = ServiceOrder.findServiceOrder(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'ServiceOrder' with identifier '" + id + "'", ServiceOrder.findServiceOrder(id));
    }
    
}
