// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.mcel2.domain;

import com.mcel2.domain.UserType;
import com.mcel2.domain.UserTypeDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect UserTypeDataOnDemand_Roo_DataOnDemand {
    
    declare @type: UserTypeDataOnDemand: @Component;
    
    private Random UserTypeDataOnDemand.rnd = new SecureRandom();
    
    private List<UserType> UserTypeDataOnDemand.data;
    
    public UserType UserTypeDataOnDemand.getNewTransientUserType(int index) {
        UserType obj = new UserType();
        setDescription(obj, index);
        setLevelOrdinal(obj, index);
        return obj;
    }
    
    public void UserTypeDataOnDemand.setDescription(UserType obj, int index) {
        String description = "description_" + index;
        obj.setDescription(description);
    }
    
    public void UserTypeDataOnDemand.setLevelOrdinal(UserType obj, int index) {
        Integer levelOrdinal = new Integer(index);
        obj.setLevelOrdinal(levelOrdinal);
    }
    
    public UserType UserTypeDataOnDemand.getSpecificUserType(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        UserType obj = data.get(index);
        Long id = obj.getId();
        return UserType.findUserType(id);
    }
    
    public UserType UserTypeDataOnDemand.getRandomUserType() {
        init();
        UserType obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return UserType.findUserType(id);
    }
    
    public boolean UserTypeDataOnDemand.modifyUserType(UserType obj) {
        return false;
    }
    
    public void UserTypeDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = UserType.findUserTypeEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'UserType' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<UserType>();
        for (int i = 0; i < 10; i++) {
            UserType obj = getNewTransientUserType(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
